version: "2.4"
services:
  web:
    build:
      context: web
      dockerfile: dockerfile
    ports:
      - "3000:3000"
  api:
    build:
      context: api
      dockerfile: dockerfile
    ports:
      - "3001:3001"